## Getting hands-on with NumPy


This assignment aims at acquainting you with numpy methods which you will require during this project. So, it is advised that you follow the instructions before each code cell diligently.<br>
You are encouraged to google (or ChatGPT) things up wherever you feel stuck : )<br>
But make sure you understand things and not just copy-paste them


### **Import the NumPy library**


In [1]:
import numpy as np


### **Initialising arrays in NumPy**


NumPy offers several way to initialise arrays

- Create a $2\times3$ array identical to
  $\begin{bmatrix}
1 & 2 & 4\\
7 & 13 & 21\\
\end{bmatrix}$ and a $2\times2\times3$ array identical to
  $\begin{bmatrix}
[1 & 2 & 3] & [4 & 5 & 6]\\
[7 & 8 & 9] & [10 & 11 & 12]\\
\end{bmatrix}$


In [ ]:
# START
    # Enter the values for the 2x3 array
arr1 = np.array([[1, 2, 4], [7, 13, 21]])
    # Similarly initialise the second array and assign it to arr2
arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# END

print("arr1:\n", arr1)
print("Shape of arr1:", arr1.shape, "; No. of Dimensions:", arr1.ndim)
print("arr2:\n", arr2)
print("Shape of arr2:", arr2.shape, "; No. of Dimensions:", arr2.ndim)


arr1:
 [[ 1  2  4]
 [ 7 13 21]]
Shape of arr1: (2, 3) ; No. of Dimensions: 2
arr2:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of arr2: (2, 2, 3) ; No. of Dimensions: 3


Note that the shapes and no. of dimensions of the arrays have been printed. These attributes help a lot in debugging


Now create

- A $2\times3$ array **arr3** of all zeros using **np.zeros**
- A $2\times3$ array **arr4** of all ones using **np.ones**
- A $2\times3$ array **arr5** of all fives using **np.full**
- A 1-D array **arr6** containing only even numbers in the range $0-20$ using **np.arange**
- Repeat last task using **np.linspace** and name it **arr7**


In [11]:
# START
arr3 = np.zeros((2,3))
arr4 = np.ones((2,3))
arr5 = np.full((2, 3), 5)
arr6 = np.arange(0, 21, 2)
arr7 = np.linspace(0, 20, num=11)
# END

print(f"arr3: {arr3}")
print(f"arr4: {arr4}")
print(f"arr5: {arr5}")
print(f"arr6: {arr6}")
print(f"arr7: {arr7}")


arr3: [[0. 0. 0.]
 [0. 0. 0.]]
arr4: [[1. 1. 1.]
 [1. 1. 1.]]
arr5: [[5 5 5]
 [5 5 5]]
arr6: [ 0  2  4  6  8 10 12 14 16 18 20]
arr7: [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


Creating arrays with random values

- Create a $2\times3$ array **arr8** using **np.random.rand**
- Create a $2\times3$ array **arr9** with rnadom integer values in $[5,8)$ using **randint** method of **random** module


In [18]:
# START
arr8 = np.random.rand(2,3)
arr9 = np.random.randint(5,8,(2,3))
# END

print(arr8)
print(arr9)


[[0.84341246 0.49387978 0.2751486 ]
 [0.56293821 0.74683325 0.47783612]]
[[5 7 7]
 [5 7 5]]


### **Accessing arrays in NumPy**


Initialise an array **arr** $=
\begin{bmatrix}
1 & 3 & 5 & 7\\
9 & 11 & 13 & 15\\
17 & 19 & 21 & 23
\end{bmatrix}$ and perform the following operations:<br>

- Extract and print the element 13 using numpy array indexing
- Use array slicing to print only the 2nd and 4th columns of only the 2nd and 3rd rows of _arr_
- Print all the values in _arr_ which are a multiple of 3


In [ ]:
arr = np.array([
    [1, 3, 5, 7],
    [9, 11, 13, 15],
    [17, 19, 21, 23]
])

element_13 = arr[1, 2]
print("Element 13:", element_13)

sliced_part = arr[1:3, [1, 3]]
print("\n2nd and 4th columns of 2nd and 3rd rows:")
print(sliced_part)

multiples_of_3 = arr[arr % 3 == 0]
print("\nValues in arr that are multiples of 3:")
print(multiples_of_3)


Element 13: 13

2nd and 4th columns of 2nd and 3rd rows:
[[11 15]
 [19 23]]

Values in arr that are multiples of 3:
[ 3  9 15 21]


### **Reshaping and Broadcasting**


- Reshape _arr_ into a $2\times6$ matrix and print it
- Print the transpose of _arr_


In [22]:
reshaped_arr = arr.reshape(2, 6)
print(reshaped_arr)

transposed_arr = arr.T
print(transposed_arr)


[[ 1  3  5  7  9 11]
 [13 15 17 19 21 23]]
[[ 1  9 17]
 [ 3 11 19]
 [ 5 13 21]
 [ 7 15 23]]


Moving on to broadcasting, you are given two arrays **a** $=
\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}$ and **b** $=
\begin{bmatrix}
4\\
5
\end{bmatrix}$<br>

Try adding these two arrays using **+** operator and print the result


In [23]:
a = np.array([1,2,3])
b = np.array([4,5]).reshape(2,1)
print(a+b)


[[5 6 7]
 [6 7 8]]


You will find that NumPy repeats the values for the arrays to match dimensions and be compatible while doing a particular matrix operation. In general, a dimension is compatible if it is equal to the respective dimension of the other array or if it is 1


### **Miscellaneous**


Be cautious while multiplying matrices and don't confuse the functions doing element wise multiplication with the ones doing traditional matrix multipication.


In [24]:
a = np.array([1,2,3])


In [29]:
# Use np.multiply and the * operator to multiply 'arr' and 'a' in this cell, note that you may need to take transpose of one or the other matrix during this operation
b = np.multiply(arr.T,a)
print(b)
c = arr.T*a
print(c)


[[ 1 18 51]
 [ 3 22 57]
 [ 5 26 63]
 [ 7 30 69]]
[[ 1 18 51]
 [ 3 22 57]
 [ 5 26 63]
 [ 7 30 69]]


In [30]:
# Use np.matmul and np.dot functions to multiply 'arr' and 'a' in this cell, again you may need to take transpose of one or the other matrix
d = np.matmul(arr.T,a)
print(d)
e = np.dot(arr.T,a)
print(e)


[ 70  82  94 106]
[ 70  82  94 106]
